### ISSUE TITLE
Syntax error in function definition?

### ISSUE THREAD

**Issue by j00bar** [Lucretiel/autocommand#10]
```
$ sudo pip install autocommand
Downloading/unpacking autocommand
  Downloading autocommand-2.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/autocommand/setup.py) egg_info for package autocommand
    
Installing collected packages: autocommand
  Running setup.py install for autocommand
      File "/usr/local/lib/python2.7/dist-packages/autocommand.py", line 194
        module=None, *,
                      ^
    SyntaxError: invalid syntax
    
    
Successfully installed autocommand
Cleaning up...
```

**Comment by Lucretiel** [comment]
What version of Python is this on? That's the keyword-only argument syntax that was added in [PEP 3102](https://www.python.org/dev/peps/pep-3102/) to Python 3. I made the decision to have this library be Python 3 only, so that [`inspect.signature`](https://docs.python.org/3/library/inspect.html#inspect.signature) can be used instead of the much more unwieldy [`getfullargspec`](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec).

**Comment by j00bar** [comment]
Py2.7 - so I suppose disregard. Thanks!
